### ISSUE TITLE
Application runs fine but no video (likely Widevine issue)

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#1]
I am using the last version currently on Github and running it on Solus x64 using the npm commands. The applications opens correctly and does see the current live programs, but will fail at streaming them. I am expecting it is due to Widevine, but the `linux-setup.sh` script fails, presumably because the Chrome version that wget is trying to get does not exist anymore.

I have tried manually putting the libwidevinecdm.so into ~/.viatcheslav/scripts/widevine and running the application with `WIDEVINE_PATH=`, but I still have the same issue.

Also, there is no linux-run script in scripts/, is that normal?

Thanks for this application by the way, I'd really like to make it work and replace Molotov. Hope it is still maintained.

**Comment by Rudloff** [comment]
Hello,
I updated the build script. Can you try again?

As for the linux-run script, it is defined here (and does not use an external script file): https://github.com/Rudloff/viatcheslav/blob/master/package.json#L35

**Comment by Kabouik** [comment]
Excellent, it does work with the `develop` branch, the linux-setup script worked fine and linux-run makes the application run and stream correctly. You can't imagine how glad I am that you came up with this open source alternative, hope it'll live long!

(Isn't Molotov.tv service only for French TV? I guess I could have asked my initial question in French after all.)

**Comment by Rudloff** [comment]
Oui, je suis français :)
