### ISSUE TITLE
Live streams and replays seem to be broken

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#10]
Hey @Rudloff, 

Still using Viatcheslav very often, so here's a good occasion to thank you again for this open source alternative to Molotov. However, the compatibility with molotov.tv seems to have broken again, this time both for live streams and replays, and for all the channels I tested. The grid of programs is successfully loaded, but starting the video will always fail on my computers (I tested two, with two different FAIs).

Did molotov.tv change something again and can it be worked around to restore the compatibility with Viatcheslav?

Thanks.

**Comment by Rudloff** [comment]
Hello,

I have no idea why it does not work anymore :slightly_frowning_face: 
I could not find anything helpful in the logs.

The only strange thing I found is that requests to https://lic.drmtoday.com/license-proxy-widevine/cenc/ are rejected, but I don't know why. (It is a service that handles DRM files licencing so it might explain why videos are not played correctly.)

**Comment by Kabouik** [comment]
Sad face. :<

**Comment by Rudloff** [comment]
I think I found a solution.
Requirements for playing DRM-protected content in Electron changed, but there is [an Electron fork](https://github.com/castlabs/electron-releases) that makes it easier.

Can you try the latest develop to see if it works for you too?

**Comment by Kabouik** [comment]
Ha! I knew coming back one month later to whine was worth it!

I'll try later tonight @Rudloff, thanks.

**Comment by Kabouik** [comment]
Seems to work, thanks again @Rudloff.

**Comment by Rudloff** [comment]
Great! I will publish a new release then.
