### ISSUE TITLE
Empty window with no content displayed

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#11]
Hey @Rudloff, here's my monthly report of a new issue after molotov.tv breaks the compatibility with third party apps again! Since today (or maybe just a couple days ago), Viatcheslav stopped displaying the content of molotov.tv again:

![image](https://user-images.githubusercontent.com/7107523/55294287-94852e00-5400-11e9-9f2a-3b1a9784aab8.png)

Also, a more minor issue: in one of the commits you made a few months ago to fix an issue with the layout, you added a grey block at the top of the interface in order to push the content down and avoid some elements to superimpose. However, the offset is also visible and wastes some of the screen estate when using the full screen mode (F11). Would you have a more elegant workaround in mind?

**Comment by Rudloff** [comment]
Molotov is looking for a variable that does not exist in Viatcheslav. It should be fixed on the develop branch now.

As for the space on top, it is not caused by my workaround. This space is used to display the window buttons in the official app (Viatcheslav uses native windows buttons, but in the official app the buttons are included in the webview).
I will see if I have a simple way of removing it.

**Comment by Kabouik** [comment]
Confirmed to work perfectly with `develop`. Thanks again for the swift fixes @Rudloff!

**Comment by Rudloff** [comment]
I pushed a workaround for the margin issue on develop. Can you check if it works for you?

**Comment by Kabouik** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Seems to work pretty well, thanks. 

However I'm getting several warnings at `npm install` that `npm
audit fix` (including with the `--force` argument) doesn't seem
to fix. I am not sure it is related, but just in case:

```
kabouik@xiaomimi-solus ~/.config/viatcheslav $ npm install

> electron@4.0.4-wvvmp postinstall /home/kabouik/.config/viatcheslav/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should
commit this file. added 338 packages from 512 contributors and
audited 723 packages in 14.389s found 7 vulnerabilities (2 low, 2
moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```


Pierre Rudloff <notifications@github.com> wrote:
> I pushed a workaround for the margin issue on develop. Can you
> check if it works for you?
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQGcBAEBCgAGBQJcpS33AAoJEMyT6hBwkOW0mzUL/0NmHH76fcoP2ZObfVWymyEo
/xUPt4pQCY8u3fc9f7ndBn14HXQ99JMXOX1gaktQVtA1hjWh7IqMChEGgxzsZ7rn
z8kCtJZkUI3+/GpQGhB8UUAJF40i3+L0PnPN0Eop94HmcLRrcnUmBuogJyExkoJf
rBp6P6lE2o2JTAp+UPkDLra2ayaRURAIHNf4G+YYcoLzYNbuviVbzCJe19b5ou12
chegdixo1tE7Xn2dOEpN7mjR2YGFtxbCKW7D1ukh5QzO0FfefEHUiRb5e1GCgq9F
zjnCZe46hMUVucdMWBRVurfgoL3BNd2GVO+vHoUB5g58L90+uJx6kNyXIkbP5EFS
vk9qSMb0w5hq4H/NdEirxpLrbhilZFgV/48KeWQOD9Q3PAvGQapScqEzyzk/G43/
HtRY3G7KfSdi2EU+/JYPm/3I2qN5jpx5ARQ0zAkXp0+5AoM+UE8CsUNs8uOkzmlm
dYuI86W4ykJFlH8Agg0DDnSOH/T8LLkBsJbV4l+w8A==
=Ujvt
-----END PGP SIGNATURE-----

**Comment by Kabouik** [comment]
Seems to work pretty well, thanks. 

However I'm getting several warnings at `npm install` that `npm audit fix` (including with the `--force` argument) doesn't seem to fix. I am not sure it is related, but just in case:

```
kabouik@xiaomimi-solus ~/.config/viatcheslav $ npm install

> electron@4.0.4-wvvmp postinstall /home/kabouik/.config/viatcheslav/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should
commit this file. added 338 packages from 512 contributors and
audited 723 packages in 14.389s found 7 vulnerabilities (2 low, 2
moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by Rudloff** [comment]
Thanks for telling me. I will try to update some of the dependencies, then I will publish a new release.

**Comment by Kabouik** [comment]
Unfortunately, seems to be broken again @Rudloff. Hope you don't mind fixing things up every time Molotov.tv do their shenanigans.
