### ISSUE TITLE
Empty Electron window

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#12]
I posted into #11 because the issue is back, but I am not sure you receive notifications for closed issues, so here is a new one just in case.

**Comment by Rudloff** [comment]
Hello,

Sorry, I saw your message but forgot to have a look at the problem.
This should now be fixed on the developer branch.

For some reason, the Molotov JS was trying to insert HTML in a block that does not exist in the web app (it is probably added by the official Electron app).

**Comment by Kabouik** [comment]
Thanks, and sorry for the late reply. I can confirm it works with the develop branch.
