### ISSUE TITLE
Stopped working a few days/weeks ago

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#5]
I usually use Viatcheslav daily or every other day, but have not used it since the end of 2017. I noticed today that it now gives me an error when trying to stream a channel, on two independent computers both running Solus OS. The git repository is up to date. The error message is just "Veuillez nous excuser pour la gêne occasionnée" from the Electron interface, but every component of the interface works normally; just not the streaming.

I have tried updating Widevine with `npm run linux-setup` but I get the following error:

```
kabouik@solus-desktop ~/.viatcheslav $ npm run linux-setup

> viatcheslav@0.1.2 linux-setup /home/kabouik/.viatcheslav
> scripts/linux-setup.sh

--2018-01-04 18:12:58--  https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_61.0.3163.100-1_amd64.deb
Resolving dl.google.com... 172.217.23.14, 2a00:1450:4009:801::200e
Connecting to dl.google.com|172.217.23.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-04 18:12:59 ERROR 404: Not Found.

ar: google-chrome-stable_61.0.3163.100-1_amd64.deb: File format not recognized
```

I'm guessing it's just that the Chrome version number has to be changed in the script? Wouldn't there be a way to fetch the latest version without actually having to manually type in the number?
  
  [Edit] Molotov still works, although I have not updated it in months.

**Comment by Rudloff** [comment]
I updated the `linux-setup` script so that it always downloads the latest stable version of Chrome.

I'm also getting the same Molotov error, I need to investigate this further.

**Comment by Rudloff** [comment]
I think I found the issue. @Kabouik, can you check on the develop branch if it works for you?

(Also I replaced the `linux-setup` script with an NPM package that does the same thing, so you just need to run `npm install` and it will install Widevine.)

**Comment by Kabouik** [comment]
Unfortunately it seems I can't log in with my account when I clone the develop branch of Viatcheslav, the pop-up window asking for either a Facebook or Gmail account disappears when I click on either one, and if I just type my credentials without selecting one, then Molotov won't find my account.

Also, I got this:
```
kabouik@solus-desktop ~/.config/viatcheslav $ npm install

> electron@1.7.10 postinstall /home/kabouik/.config/viatcheslav/node_modules/electron
> node install.js


> electron-widevinecdm@5.0.2 postinstall /home/kabouik/.config/viatcheslav/node_modules/electron-widevinecdm
> node install.js

Downloading widevinecdm_darwin_x64.zip...
Downloading widevinecdm_win32_x64.zip...
Downloading widevinecdm_win32_ia32.zip...
Downloading widevinecdm_linux_x64.zip...
widevinecdm_darwin_x64.zip is downloaded & extracted.
widevinecdm_win32_ia32.zip is downloaded & extracted.
widevinecdm_linux_x64.zip is downloaded & extracted.
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-widevinecdm@5.0.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-widevinecdm@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kabouik/.npm/_logs/2018-01-04T23_16_16_132Z-debug.log
```
 Here is the log file: [Part 1](https://hastebin.com/oveyifixok.pl), [Part 2](https://hastebin.com/nomavupake.sql) (the username is different from above where I replaced it manually with "Kabouik" to be consistent with my previous post, don't pay attention to it).

**Comment by Rudloff** [comment]
Indeed, Facebook and Google login does not work. It would require additional code.
However, standard e-mail/password login works for me.

**Comment by Kabouik** [comment]
Oh right, silly me. Turns out I am using a regular account with Molotov, forgot about what account I had for Molotov and was trying something wrong, sorry for the stupid remark.

I can confirm that the develop branch works correctly (I had to run `npm install` again after the error above and it finally worked correctly, perhaps an Internet connection issue). Thanks for the very swift update.
