### ISSUE TITLE
No live streaming anymore

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#7]
Hi,

I'm still using Viatcheslav almost daily but it has stopped working lately for live streams on all channels I tried. Replays seem to work correctly.

![](https://REHO.ST/0x0.st/sL_a.png)

This issue is not unusual, but it usually disappears after a few hours as if the problem originates from Molotov's service itself. However, here, the Molotov application works flawlessly (although I haven't updated it in months), and Viatcheslav still fails several hours later so I'm not sure the website would be down so long. Not sure how to debug it but I'm sure you would quickly see what is wrong @Rudloff. :]

Cheers!

**Comment by Rudloff** [comment]
Molotov now checks for some app ID sent by the client. I used the same as the official app it works again.
I will publish a new release with the fix.

**Comment by Kabouik** [comment]
Thanks, just git pulled and can confirm it fixed the issue on my end as well.

**Comment by Kabouik** [comment]
Seems the same thing happened again (replays play properly, live streaming fails).

**Comment by Rudloff** [comment]
I can't reproduce this, live streaming works for me.

**Comment by Kabouik** [comment]
My git folder was up to date but I was not using the same computer as last time, so maybe something was missing, maybe I needed to `npm install` again. I have removed my viatcheslav folder and started over with `git clone` and `npm install`. Now it's working again. Sorry about the false alarm, hope you have not spent too long trying to reproduce it.

**Comment by Rudloff** [comment]
Don't worry, it only took me 5 minutes to test it :wink:
