### ISSUE TITLE
Thumbnails are too small and content does not adjust to the window size anymore

### ISSUE THREAD

**Issue by Kabouik** [Rudloff/viatcheslav#8]
Hi,

The title says it all, but here are two pictures showing the issue:

![screenshot from 2018-06-26 19 50 46](https://user-images.githubusercontent.com/7107523/41930083-4cc29154-797a-11e8-98db-f17cb362e55d.png)
![screenshot from 2018-06-26 19 50 56](https://user-images.githubusercontent.com/7107523/41930086-4da03af4-797a-11e8-9478-81b1c273102b.png)

A video playing in fullscreen (F11) will also stay at its original size instead of scaling with the screen, if it was started from the "Chaînes" section (when started from "Regarder la TV", it won't appear constrained in the same way, but will show up only at certain window sizes). It's new from today or yesterday, I suppose they changed something on the website.

**Comment by Rudloff** [comment]
For some reason, their code does not get the window size correctly but I didn't find a way to fix it.
So instead I added a CSS workaround that does the trick for now.

Can you try if a26d39a4688f4b4ca76deb44fb656f6173d21b32 works for you?

(It does not work everytime, especially when you reload the app. If it does not work, try to resize the window and the fix should apply.)

**Comment by Kabouik** [comment]
I have switched to `develop` branch but the display is still very wonky, thumbnails are never at the correct size and the screen estate is not properly used. All thumbnails seem to show up though, whereas you could see on the sreenshots above that many did not appear.

**Comment by Rudloff** [comment]
After a lot of debugging, I think I finally found the problem. The official app injects some CSS in the webview and without it the design breaks.

Can you pull 2490c338607cce3a50840bee27ad85414ef4a21b and see if it works for you?

**Comment by Kabouik** [comment]
That's a bit stupid but I'm not very experienced with the git workflow. Could you please tell me how I pull a single commit from a different branch if my local folder is pulled from `master`?

**Comment by Rudloff** [comment]
Don't worry, that's not a stupid question (and Git is not always straightfoward).
You can do it like this:
```bash
git fetch origin
git checkout 2490c338607cce3a50840bee27ad85414ef4a21b
```

And when you want to go back to `master`:
```bash
git checkout master
```

**Comment by Kabouik** [comment]
Thanks, I can confirm that `2490c338607cce3a50840bee27ad85414ef4a21b` fixed the issue on my end. Well done!
